[package]
name = "to_do_list"
version = "1.0.0"
authors = []

[addresses]
to_do_list='c4645e7b54fcd6dd6b0f1d4ad87474b9bfb3f0abf0b97d33cb79caa482215cfa'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
